### ISSUE TITLE
release management functionality seems to fail if the TeamCity project uses an uploaded private key

### ISSUE THREAD

**Issue by paulmwestwood** [JFrogDev/teamcity-artifactory-plugin#15]
Hi, we are using TeamCity 9.04, and currently have a Windows master and a RHEL agent. We're checking out from GitLab, and using an attached private key to authenticate. This works fine for plain builds (mvn clean package etc), but when we attempt to use the release management functionality in the plugin, we get something like:

[Step 1/1] org.jfrog.teamcity.agent.release.vcs.git.GitException: Git command '[git, push, git@code.europe.***.local:EI/traveldataexchangeintiator.git, refs/heads/REL-BRANCH-traveller-data-exchange-initiator-1.2]' returned status code '128': Host key verification failed.
fatal: Could not read from remote repository.

Interestingly, this happens on the attempted push of the new branch at the end of the build, not on the checkout. TeamCity docs say that the private key is copied to the agent for the git checkout, but then removed; is it possible it's being removed before the push of the new branch?

I have got this working by adding the private key to the agent ~/.ssh directory directly, but obviously I'd prefer not to have to do this. Is there any way around this? 

Thanks for your help ,Paul

**Comment by eyalbe4** [comment]
Currently the Artifactory Plugin does not copy the SSH key to the agent during the Release Management process, prior to pushing the branch, so you do need to have it on the agent machine.
Regardless of this issue, we are planning to start supporting http/https (and not only ssh) for Release Management as part of the next plugin release.
